---
title: "Dashboard!!!"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)

library(plotly)

data("Instacart")

janitor::clean_names(instacart)
```

```{r}
instacart_ = 
  instacart |> 
  select(order_hour_of_day, department, days_since_prior_order)

```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
instacart |> 
  count(department) |> 
  mutate(department = fct_reorder(department, n)) |> 
  plot_ly(
    x = ~ department, y = ~n, color = ~department,
    type = "bar")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
instacart_ |> 
  plot_ly( 
    x = ~order_hour_of_day, type = "histogram", 
    marker = list(color = "pink",line = list(color = "grey",width = 2))) |>
  layout(title = "Hours At Which Orders Were Placed",
         xaxis = list(title = "Order Hours"),
         yaxis = list(title = "Frequency"))
```

### Chart C

```{r}
instacart |> 
  plot_ly(
    x = ~department, y = ~days_since_prior_order, color = ~department,
    type = "box")
```

